#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  mi_network:

services:
  orderer.leonimurilo.com:
    container_name: orderer.leonimurilo.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/configtx/:/etc/hyperledger/configtx
        - ./config/crypto-config/ordererOrganizations/leonimurilo.com/orderers/orderer.leonimurilo.com/:/etc/hyperledger/msp/orderer
        # - ./config/crypto-config/peerOrganizations/org1.leonimurilo.com/peers/peer0.org1.leonimurilo.com/:/etc/hyperledger/msp/peerOrg1
    networks:
      - mi_network

  # =========== Supplier 1
  peer0.supplier1.leonimurilo.com:
    container_name: peer0.supplier1.leonimurilo.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.supplier1.leonimurilo.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Supplier1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.supplier1.leonimurilo.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_mi_network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.supplier1.leonimurilo.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./config/crypto-config/peerOrganizations/supplier1.leonimurilo.com/peers/peer0.supplier1.leonimurilo.com/msp:/etc/hyperledger/msp/peer
        - ./config/crypto-config/peerOrganizations/supplier1.leonimurilo.com/users:/etc/hyperledger/msp/users
        - ./config/configtx:/etc/hyperledger/configtx
    depends_on:
      - orderer.leonimurilo.com
      - couchdb.supplier1.leonimurilo.com
    networks:
      - mi_network

  ca.supplier1.leonimurilo.com:
    container_name: ca.supplier1.leonimurilo.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.leonimurilo.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.supplier1.leonimurilo.com-cert.pem
      # TODO change keyfile when generated
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4239aa0dcd76daeeb8ba0cda701851d14504d31aad1b2ddddbac6a57365e497c_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./config/crypto-config/peerOrganizations/supplier1.leonimurilo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - mi_network

  couchdb.supplier1.leonimurilo.com:
    container_name: couchdb.supplier1.leonimurilo.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - mi_network

  cli.supplier1.leonimurilo.com:
    container_name: cli.supplier1.leonimurilo.com
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli.supplier1.leonimurilo.com
      - CORE_PEER_ADDRESS=peer0.supplier1.leonimurilo.com:7051
      - CORE_PEER_LOCALMSPID=Supplier1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supplier1.leonimurilo.com/users/Admin@supplier1.leonimurilo.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../mi-smart-contract/:/opt/gopath/src/github.com/
        - ./config/configtx:/etc/hyperledger/configtx/
        - ./config/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - mi_network
    #depends_on:
    #  - orderer.leonimurilo.com
    #  - peer0.supplier1.leonimurilo.com
    #  - couchdb.supplier1.leonimurilo.com

  # =========== Supplier 2
  peer0.supplier2.leonimurilo.com:
    container_name: peer0.supplier2.leonimurilo.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.supplier2.leonimurilo.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Supplier2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.supplier2.leonimurilo.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_mi_network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.supplier2.leonimurilo.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./config/crypto-config/peerOrganizations/supplier2.leonimurilo.com/peers/peer0.supplier2.leonimurilo.com/msp:/etc/hyperledger/msp/peer
        - ./config/crypto-config/peerOrganizations/supplier2.leonimurilo.com/users:/etc/hyperledger/msp/users
        - ./config/configtx:/etc/hyperledger/configtx
    depends_on:
      - orderer.leonimurilo.com
      - couchdb.supplier2.leonimurilo.com
    networks:
      - mi_network

  ca.supplier2.leonimurilo.com:
    container_name: ca.supplier2.leonimurilo.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.supplier2.leonimurilo.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.supplier2.leonimurilo.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4239aa0dcd76daeeb8ba0cda701851d14504d31aad1b2ddddbac6a57365e497c_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./config/crypto-config/peerOrganizations/supplier2.leonimurilo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - mi_network

  couchdb.supplier2.leonimurilo.com:
    container_name: couchdb.supplier2.leonimurilo.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984
    networks:
      - mi_network

  cli.supplier2.leonimurilo.com:
    container_name: cli.supplier2.leonimurilo.com
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli.supplier2.leonimurilo.com
      - CORE_PEER_ADDRESS=peer0.supplier2.leonimurilo.com:7051
      - CORE_PEER_LOCALMSPID=Supplier2MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supplier2.leonimurilo.com/users/Admin@supplier2.leonimurilo.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../mi-smart-contract/:/opt/gopath/src/github.com/
        - ./config/configtx:/etc/hyperledger/configtx/
        - ./config/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - mi_network
    #depends_on:
    #  - orderer.leonimurilo.com
    #  - peer0.supplier2.leonimurilo.com
    #  - couchdb.supplier2.leonimurilo.com

  # =========== City 1
  peer0.city1.leonimurilo.com:
    container_name: peer0.city1.leonimurilo.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.city1.leonimurilo.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=City1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.city1.leonimurilo.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_mi_network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.city1.leonimurilo.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./config/crypto-config/peerOrganizations/city1.leonimurilo.com/peers/peer0.city1.leonimurilo.com/msp:/etc/hyperledger/msp/peer
        - ./config/crypto-config/peerOrganizations/city1.leonimurilo.com/users:/etc/hyperledger/msp/users
        - ./config/configtx:/etc/hyperledger/configtx
    depends_on:
      - orderer.leonimurilo.com
      - couchdb.city1.leonimurilo.com
    networks:
      - mi_network

  ca.city1.leonimurilo.com:
    container_name: ca.city1.leonimurilo.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.city1.leonimurilo.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.city1.leonimurilo.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4239aa0dcd76daeeb8ba0cda701851d14504d31aad1b2ddddbac6a57365e497c_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./config/crypto-config/peerOrganizations/city1.leonimurilo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - mi_network

  couchdb.city1.leonimurilo.com:
    container_name: couchdb.city1.leonimurilo.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 9984:5984
    networks:
      - mi_network

  cli.city1.leonimurilo.com:
    container_name: cli.city1.leonimurilo.com
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli.city1.leonimurilo.com
      - CORE_PEER_ADDRESS=peer0.city1.leonimurilo.com:7051
      - CORE_PEER_LOCALMSPID=City1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/city1.leonimurilo.com/users/Admin@city1.leonimurilo.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../mi-smart-contract/:/opt/gopath/src/github.com/
        - ./config/configtx:/etc/hyperledger/configtx/
        - ./config/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - mi_network
    #depends_on:
    #  - orderer.leonimurilo.com
    #  - peer0.city1.leonimurilo.com
    #  - couchdb.city1.leonimurilo.co
